### ISSUE TITLE
What do the x and y axises mean on the performance graphs?

### ISSUE THREAD

**Issue by grepsedawk** [zwilias/elm-faster-map#1]
The performance is shown as faster, but what are the x and y axises? Are they the total count mapped over and a unit of time?

**Comment by zwilias** [comment]
> ilias [10:15 PM]
Horizontal is the size of the list, vertical is the number of list-items processed per second.
For very small lists, things like the overhead of calling a function dominate. When you go a little further along, things tend to settle a bit. Eventually, garbage collection needs to kick in every now and then because `foldr` and `map` tend to create intermediate structures and as the sizes grow, so does the generated garbage. 

Note that both axes are logarithmic. This makes the plots a little harder to interpret, but it looked prettied. So for example for `List.foldr` with a `List` with 10.000 entries, this means that the "next implementation in `elm-lang/core`" (`next`, the yellow line) is able to process ~3.000 elements per second, while the implementation in this repo manages ~30.000 elements per second.

**Comment by grepsedawk** [comment]
Thanks for your very informative reply, it was helpful!
